# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
- stage: build
  displayName: Build Stage
  jobs:
  - job: AngularBuild
    steps:
      - task: NodeTool@0
        inputs:
         versionSpec: '10.x'
        displayName: 'Install Node.js'
      
      #shell script to install node modules and ng build
      - script: | 
          npm install
          npm run build
        displayName: 'npm install and build'
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '/home/vsts/work/1/s/dist/**'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'drop'
          publishLocation: 'Container'

- stage: release
  dependsOn: build
  displayName: Release onto tomcat
  jobs:
    - deployment: deployment_onto_tomcat
      displayName: WebAppDeployment
      environment: uat
      pool: 
        vmImage: ubuntu-latest
      strategy:
       runOnce:
         deploy:
           steps:
            - task: DownloadBuildArtifacts@1
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                itemPattern: 'dist/**'
                downloadPath: '$(System.ArtifactsDirectory)'
                
  
            - task: WindowsMachineFileCopy@2
              inputs:
                SourcePath: '$(System.ArtifactsDirectory)'
                MachineNames: '20.121.220.34'
                AdminUserName: $(username)
                AdminPassword: $(password)
                TargetPath: 'C:/programfiles'
                CleanTargetBeforeCopy: true
          

 